version: "3"
services:
  db:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: adb
    ports:
      - 3306:3306
  fampay:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - 8087:8087